
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.net.Socket;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhannad Saqib
 */
public class messenger extends javax.swing.JFrame {

    /**
     * Creates new form messenger
     */
    public messenger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BListen = new javax.swing.JButton();
        TFPort = new javax.swing.JTextField();
        TFFriendIP = new javax.swing.JTextField();
        TFFriendPort = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAMessage = new javax.swing.JTextArea();
        TFMessage = new javax.swing.JTextField();
        BSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BListen.setText("Listen");
        BListen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BListenActionPerformed(evt);
            }
        });

        TFPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPortActionPerformed(evt);
            }
        });

        TFFriendIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFFriendIPActionPerformed(evt);
            }
        });

        TAMessage.setColumns(20);
        TAMessage.setRows(5);
        jScrollPane1.setViewportView(TAMessage);

        BSend.setText("Send");
        BSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BListen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFPort, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFFriendIP, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFFriendPort))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TFMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BSend, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BListen)
                    .addComponent(TFPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFFriendIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFFriendPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSend))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPortActionPerformed

    private void TFFriendIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFFriendIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFriendIPActionPerformed

    private void BListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BListenActionPerformed
        if(server!=null)
        {
            try{
            server.close();
            } catch (IOException ex) {
                Logger.getLogger(messenger.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
               int port=0;
        try{
            port = Integer.parseInt( TFPort.getText());
               server=new ServerSocket(port);
               TAMessage.setText("Now Listening To Port "+ port+"\n");
          } catch (IOException ex ) {
                TAMessage.append("Unable To Listen at Port "+port+"\n");
            }
        catch (         java.lang.NumberFormatException ex ) {
                TAMessage.append("Unable To Listen at Port "+port+"\n");
            }

    }//GEN-LAST:event_BListenActionPerformed

    private void BSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSendActionPerformed
      int port=0;
        try{
           port = Integer.parseInt( TFFriendPort.getText());
          //To Comunicate at same Computer
           //InetAddress host=InetAddress.getLocalHost();
          // sender=new Socket(host.getHostName(), port);
           
          //To Comunicate at Different Computers
           sender=new Socket(TFFriendIP.getText(), port); 
          ObjectOutputStream oos=new ObjectOutputStream(sender.getOutputStream());
           oos.writeObject(TFMessage.getText());
           TAMessage.append("You : "+TFMessage.getText()+"\n");
           oos.close();
           TFMessage.setText("");
      } catch (IOException ex) {
                TAMessage.append("Unable To Send Message at Port "+port+"\n");
        }
        catch (         java.lang.NumberFormatException ex ) {   
            TAMessage.append("Unable To Send Message at Port "+port+"\n");
            }
        finally{
            if(sender!=null)
            {
                sender=null;
            }
        }
        
      
    }//GEN-LAST:event_BSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         messenger m=null;
            m=new messenger();
                m.setVisible(true);
                m.TAMessage.setText("Welcome To Messenger \nPlease Select A Port To Listen\nEnter Your Friends Ip\nAnd Your Friends Port");
        /* Create and display the form */

        while(true)
        {    System.out.print("");
             if(m.server!=null)
                {
                    Socket s=null;
                    ObjectInputStream ois=null;
                    try{
                     s=m.server.accept();                    
                     ois=new ObjectInputStream(s.getInputStream());
                    m.TAMessage.append("Your Friend: "+(String)ois.readObject()+"\n");
                    } catch (IOException ex) {
                        Logger.getLogger(messenger.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(messenger.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    finally{
                        if(s!=null)
                        {
                            try{
                            s.close();
                        }catch (IOException ex) {
                                Logger.getLogger(messenger.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        
                        }
                        if(ois!=null)
                        {
                            try{
                            ois.close();
                        }catch (IOException ex) {
                                Logger.getLogger(messenger.class.getName()).log(Level.SEVERE, null, ex);
                            }                        }
                    }
                }
        }
        
    }

    private ServerSocket server;
    private Socket   sender;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BListen;
    private javax.swing.JButton BSend;
    private javax.swing.JTextArea TAMessage;
    private javax.swing.JTextField TFFriendIP;
    private javax.swing.JTextField TFFriendPort;
    private javax.swing.JTextField TFMessage;
    private javax.swing.JTextField TFPort;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
